# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The Foundry Visionmongers Ltd#

name: Build Wheels

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

concurrency:
  # Shared with `deploy-pypi`.
  group: wheel-${{ github.ref }}
  # Cancel any in-progress build or publish.
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Download wheels from commit OpenAssetIO PR
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels.yml
          workflow_conclusion: success
          name: openassetio-wheels
          repo: OpenAssetIO/OpenAssetIO
          path: deps

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          # Use wheels from feature branch for intermediate testing
          python -m pip install ./deps/openassetio-*cp39*-manylinux_*_x86_64.whl

      - name: Build wheels
        run: pip wheel --no-deps --wheel-dir wheelhouse .

      - uses: actions/upload-artifact@v3
        with:
          name: openassetio-manager-bal-wheels
          path: ./wheelhouse/*.whl
